"""
Persistence mapping for the ``repositories`` table.

"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import CITEXT, UUID
from sqlalchemy.orm import Mapped, mapped_column

from wooloo.infrastructure.database.models.base import Base


class RepositoryModel(Base):
    """Row mapping for a container image repository.

    Attributes:
        id: Primary key, generated by the database via ``uuid_generate_v4()``
            so the value never depends on the application being the only
            writer.
        name: Repository name, for example ``acme/backend-api``. ``CITEXT``
            makes uniqueness and lookups case-insensitive in the database
            rather than relying on every caller to normalize first.
            ``index=True`` accompanies ``unique=True`` so uniqueness is
            carried by a unique *index* named ``ix_repositories_name``, not
            by a table constraint named ``uq_repositories_name``. That is
            what migration ``0002`` creates, and the persistence adapter
            reads the index name off a failed insert to tell a duplicate
            name from any other violation — so a schema built from this
            metadata instead of from the migrations has to name the object
            identically or that translation silently stops matching.
        created_at: Insert timestamp, set by the database.
        updated_at: Last-modification timestamp. Refreshed by SQLAlchemy on
            ORM-issued UPDATEs; note this is not a database trigger, so
            statements bypassing the ORM must set it themselves.
        deleted_at: Soft-deletion timestamp, ``None`` while the repository
            is live.
    """

    __tablename__ = "repositories"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v4()"),
    )

    name: Mapped[str] = mapped_column(
        CITEXT(),
        nullable=False,
        index=True,
        unique=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )
