"""
The repository domain entity.

"""

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True)
class Repository:
    """A named OCI image repository, such as ``library/nginx``.

    Attributes:
        id: Server-assigned primary key, generated by the database on insert
            rather than by the caller, so an instance of this entity only ever
            exists for a row that was actually persisted.
        name: The validated repository name, e.g. ``acme/backend-api``. Unique
            across the registry, compared case-insensitively by the database
            (``CITEXT``), and immutable once created — there is no rename
            operation.
        created_at: Timezone-aware moment the repository was inserted. Never
            changes.
        updated_at: Timezone-aware moment the row last changed. Equal to
            ``created_at`` until something mutates the row; today a soft delete
            is the only such mutation.
        deleted_at: ``None`` while the repository is active. Set once, to the
            moment of the first successful delete, and never unset or
            overwritten — a repeated delete leaves the original value intact. A
            non-``None`` value means the repository is invisible to every read
            path, so an entity carrying one is only ever seen inside the
            persistence layer, never returned to a client.
    """

    id: UUID

    name: str

    created_at: datetime

    updated_at: datetime

    deleted_at: datetime | None
